ignore-matches:
  - name: "False positive - TOKEN_REFRESH_INVALID"
    match: "TOKEN_REFRESH_INVALID"
  - name: "False positive - TOKEN_REFRESH_SUCCESS"
    match: "TOKEN_REFRESH_SUCCESS"
  - name: "False positive - TOKEN_REFRESH_FAILURE"
    match: "TOKEN_REFRESH_FAILURE"
  - name: "False positive - TOKEN_INVALID"
    match: "TOKEN_INVALID"
  - name: "False positive - INVALID_OR_EXPIRED_TOKEN"
    match: "INVALID_OR_EXPIRED_TOKEN"
  - name: "False positive - PASSWORD_CREATE_SUCCESS"
    match: "PASSWORD_CREATE_SUCCESS"
  - name: "False positive - PASSWORD_UPDATE_SUCCESS"
    match: "PASSWORD_UPDATE_SUCCESS"
  - name: "False positive - INCORRECT_CURRENT_PASSWORD"
    match: "INCORRECT_CURRENT_PASSWORD"
  - name: "False positive - PASSWORD_NOT_MATCH"
    match: "PASSWORD_NOT_MATCH"
  - name: "False positive - PASSWORD_SAME_AS_OLD"
    match: "PASSWORD_SAME_AS_OLD"
  - name: "False positive - ACCOUNT_LOCKED"
    match: "ACCOUNT_LOCKED"
  - name: "False positive - SEND_CODE_SUCCESS"
    match: "SEND_CODE_SUCCESS"
  - name: "False positive - SEND_CODE_FAILED"
    match: "SEND_CODE_FAILED"
  - name: "False positive - INVALID_OTP_CODE"
    match: "INVALID_OTP_CODE"
  - name: "False positive - EXPIRED_OTP_CODE"
    match: "EXPIRED_OTP_CODE"
