version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Nguyenloc2002
      MYSQL_DATABASE: trendista_database
      MYSQL_PASSWORD: Nguyenloc2002
    ports:
      - "3308:3306"  # ánh xạ cổng 3306 của MySQL với máy chủ local
    networks:
      - shared-network
    volumes:
      - mysql_data:/var/lib/mysql  # lưu trữ dữ liệu MySQL
      - ./init-scripts:/docker-entrypoint-initdb.d  # Mount thư mục chứa init script

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-dev
    restart: always
    ports:
      - "8080:8080"  # ánh xạ cổng 8080 của Spring Boot với máy chủ local
    networks:
      - shared-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/trendista_database  # sử dụng tên dịch vụ MySQL trong docker-compose
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Nguyenloc2002
    depends_on:
      - mysql  # đảm bảo MySQL khởi động trước
    entrypoint: ["java", "-jar", "/app/TrendistaShop.jar"]

networks:
  shared-network:
    name: shared-network
    driver: bridge

volumes:
  mysql_data:
